---
# This playbook deploys the whole application stack in this site.

- name: configure and deploy the webservers
  hosts: webservers
  remote_user: ansible
  become: yes
  become_user: root

  roles:
    - { role: ansible-nginx,            tags: ["nginx"] }